#+STARTUP: nolatexpreview

#+HTML_HEAD: <link rel="stylesheet" href="../../css/math.css" />
#+HTML_HEAD: <script src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/3.2.0/es5/tex-mml-chtml.min.js" integrity="sha512-9DkJEmXbL/Tdj8b1SxJ4H2p3RCAXKsu8RqbznEjhFYw0cFIWlII+PnGDU2FX3keyE9Ev6eFaDPyEAyAL2cEX0Q==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
#+HTML_HEAD: <script src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/3.2.0/es5/input/tex/extensions/ams.min.js" integrity="sha512-hYQ7XXWTcxv2ZqLKj/ZLf+iDlS6UDfMqGZBYViCaAEfLNVtmThtbS0HKzR1PnjMCi3N5SGEpOmEdYXInWlwqqQ==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>

#+TITLE: Analytic Number Theory Spring 2022

\(
    \newcommand{\contra}{\Rightarrow\!\Leftarrow}
    \newcommand{\R}{\mathbb{R}}
    \newcommand{\F}{\mathbb{F}}
    \newcommand{\Z}{\mathbb{Z}}
    \newcommand{\Zeq}{\mathbb{Z}_{\geq 0}}
    \newcommand{\Zg}{\mathbb{Z}_{>0}}
    \newcommand{\Req}{\mathbb{R}_{\geq 0}}
    \newcommand{\Rg}{\mathbb{R}_{>0}}
    \newcommand{\N}{\mathbb{N}}
    \newcommand{\Q}{\mathbb{Q}}
    \newcommand{\O}{\mathcal{O}}
    \newcommand{\C}{\mathbb{C}}
    \newcommand{\A}{\mathbb{A}}
    \renewcommand{\P}{\mathbb{P}}
    \renewcommand{\mod}{\text{ mod }}
    \DeclareMathOperator{\Spec}{Spec}
    \DeclareMathOperator{\Proj}{Proj}
    \DeclareMathOperator{\Ob}{Ob}
    \DeclareMathOperator{\Mor}{Mor}
    \DeclareMathOperator{\Hom}{Hom}
\)


* Dirichlet Characters
We have shown: if \(\chi \text{ mod } q\) is primitive, then
\[
    \sum_{a=1}^q \chi(a)e^{\frac{2\pi i a \ell}{q}} = \overline{\chi(\ell)}\sum_{a=1}^q \chi(a)e^{\frac{2\pi i a}{q}}
\]
since we if the character is primitive then we can just send \(\ell \mapsto \ell^{-1}\), which only works if \(\ell \neq 0 \text{ mod } q\). But if \(\ell = 0 \text{ mod } q\) and \(\chi\) is primitive, then both sides vanish, so everything is ok.

Lemma: If \(\chi\) is primitive, then
\[
    G(\chi) = \sum_{a= 1}^q \chi(a) e^{\frac{2\pi i a}{q}}
\]
satisfies that \(|\ G(\chi)| =  q^{1/2}\).

Proof: Consider
\[
    \sum_{\ell = 1}^q \left(\sum_{a=1}^q \chi(a) e^{\frac{2\pi i a \ell}{q}} \cdot \sum_{b=1}^q e^{-\frac{2\pi i b \ell}{q}}\right)
\]
We evaluate in two different ways. The first way is reducing the sum to
\[
    \sum_{\ell = 1}^q (\overline{\chi(\ell)} G(\chi)) (\chi(\ell) \overline{G(\chi)}) = \varphi(q) \vert \ G(\chi) | \ ^2
\]
and the second is
\[
    \sum_{a = 1}^q\chi(a) \sum_{b=1}^q\overline{\chi(b)}\sum_{\ell=1}^q e^{\frac{2\pi i (a - b) \ell}{q}} = \sum_{a,b, a = b \text{ mod } q} \vert \ \chi(a) \vert \ ^2 \varphi(q) = q \varphi(q)
\]
So we get what we want.

** Functional Equation and Analytic Continuations of \(L(s, \chi)\)
Recall that \(L(s, \chi) = \sum_{n=1}^\infty \frac{\chi(n)}{n^s}\). We need to handle the case when \(\chi\) is even and odd seperately.

Let us define \(\theta_\chi(y) = \sum_{n \in \Z} \chi(n) e^{-\pi n^2 y}\), and compute
\begin{align*}
    \int_0^\infty \theta_\chi (y) y^{\frac{s}{2}} \frac{dy}{y} &= 2 \int_0^\infty \sum_{n=1}^\infty \chi(n)e^{-\pi n^2 y}y^{\frac{s}{2}}\frac{dy}{y} \\
    &= 2 \pi^{-\frac{s}{2}}\sum_{n=1}^\infty\frac{\chi(n)}{n^s}\int_0^\infty e^{-y}y^{\frac{s}{2}}\frac{ds}{y} \\
    &= 2\pi^{-\frac{s}{2}}\Gamma \left(\frac{s}{2}\right)L(s, \chi)
\end{align*}

Now note that
\begin{align*}
    \theta_\chi (y)) &= \sum_{a=1}^q \chi(a) \sum_{\ell }e^{-\pi (a  + \ell q)^2 y}
\end{align*}
and when we take the Fourier transform, we see that
\[
    \widehat{F}(\ell) = \int_{-\infty}^\infty e^{-\pi(a + u q)^2 y}e^{-2 \pi i u \ell}du = \frac{e^{\frac{2\pi i a \ell}{q}}}{qy^{1/2}} e^{- \pi \left(\frac{\ell}{q  y^{1/2}}\right)^2}
\]

We can now get a functional equation for \(\theta_\chi\). In particular, we have that
\begin{align*}
    \theta_\chi(y) &= \sum_{a=1}^q \chi(a) \sum_{\ell = -\infty}^\infty e^{-\pi(a + \ell q)^2 q} = \sum_{a = 1}^q\chi(a) \sum_{\ell} F(a) \\
    &= \frac{1}{q y^{1/2}} \sum_{a=1}^q \chi(a) \sum_{\ell} e^{\frac{2 \pi i a \ell}{q}}e^{-\pi \frac{\ell ^2}{q^2 y}} \\
    &= \frac{1}{q y^{1/2}} \sum_{\ell} \sum_{a=1}^q \chi(a) e^{\frac{2 \pi i a \ell}{q}}e^{-\pi \frac{\ell ^2}{q^2 y}} \\
    &= \frac{G(\chi)}{q y^{1/2}} \sum_{\ell} \overline{\chi(\ell)} e^{-\pi \frac{\ell ^2}{q^2 y}} \\
\end{align*}
so we can see that
\[
    \theta_\chi (y) = \frac{G(\chi)}{q y^{1/2}} \theta_{\overline{\chi}}\left(\frac{1}{q^2y}\right)
\]

After we take a Mellin transform and do Riemann's trick, splitting the domain of integration on \(1/q\), we see that if \(\Lambda(s, \chi) = \pi^{-\frac{s}{2}}\Gamma(\frac{s}{2})L(s, \chi)\)q^{s/2}, \(\Lambda\) is entire! Furthermore, we have that
\[
    \Lambda(s, \chi) = \frac{q^{1/2}}{G(\overline{\chi})} \Lambda(1 - s, \overline{\chi})
\]

To handle the odd case, we need to do a little bit more work. We have to chance the test function \(e^{\pi u^2 y}\) to an odd Schwarz function, and we will win. In particular, \(ue^{-\pi u^2 y}\) is a good idea. Doing everything as above, we have that in this case,
\[
    \Lambda(s, \chi) = \pi^{-s/2} \Gamma \left(\frac{s+1}{2}\right)L(s, \chi)q^{s/2} = \frac{-i q^{1/2}}{G(\chi)}\Lambda(1-s, \overline{\chi})
\]

* The Infinitude of Primes in Arithmetic Progression
Fix \(\chi\) a character mod \(q\). Then,
\[
    \frac{L'}{L}(s, \chi) = \sum_{n=1}^\infty -\frac{\Lambda(n)}{n^s}\chi(n)
\]
and the orthogonality relations yield that
\[
    \frac{1}{\varphi(q)}\sum_{\chi \mod q}\frac{-L'}{L}(s, \chi)\overline{\chi(a)} = \sum_{n = a \mod q} \frac{\Lambda(n)}{n^s}
\]
As long as we can prove that
\[
    \lim_{s \rightarrow 1} \frac{1}{\varphi(q)}\sum_{\chi \mod q} -\frac{L'}{L}(s, \chi) = \infty
\]
Certainly this is true for the trivial character, which is the zeta function multiplied by a constant. So all we need to show is that \(L(1, \chi) \neq 0\) for any character \(\chi \) mod \(q\). But this is actually hard, so we're going to prove it a different way.

Pick \(\epsilon > 0\) fixed, and the interval \([1 - \epsilon, 1]\). If there is a real character \(\chi\) mod \(d\) which vanishes at \(B \in [ 1- \epsilon, 1]\), i.e. \(L(\beta, \chi\) = 0, then we call \(\beta\) a Siegel zero. Either there are no Siegel zeros, which implies that \(L(1, \chi) > 0\) for all \(\chi\). Otherwise, there must be a Siegel zero, with some associated character \(\chi'\).

Now, we consider a simple lemma: consider
\[
    \xi(s) = \zeta(s)L(s, \chi)L(s, \chi')L(s, \chi \cdot \chi') = \sum_{n=1}^\infty\frac{a(n)}{m^s}
\]
Then, \(a(1) = 1\) and \(a(n) \geq 0\) for all \(n \geq 2\). By the Euler product,
\[
    \xi(s) = \prod_{p} \left(1 - \frac{1}{p^{s}}\right)^{-1} \left(1 - \frac{\chi(p)}{p^{s}}\right)^{-1} \left(1 - \frac{\chi'}{p^{s}}\right)^{-1} \left(1 - \frac{\chi' \cdot \chi}{p^{s}}\right)^{-1}
\]
And since these are real valued characters, you can just try all of the combinations to see that the lemma holds. But then, it must be true that \(\xi(\beta) =0 \), since \(L(\beta, \chi') = 0\). Then, we have that
\[
    1 \ll \frac{1}{2\pi i}\int_{2 - i \infty}^{2 + i \infty} \xi(s + \beta) d^{10s}\frac{ds}{s(s+1)(s+2)(s+3)(s+4)}
\]
and shifting the line of integration we see that this becomes
\[
    \frac{L(1, \chi)L(1, \chi')L(1, \chi \cdot \chi')d^{10(1 - \beta)}}{(1 - \beta)(2 - \beta)(3 - \beta)(4 - \beta)(5 - \beta)} + \frac{1}{2\pi i}\int_{-\beta - i \infty}^{\beta + i \infty} \frac{\xi(s + \beta) d^{10s}ds}{s(s+1)(s+2)(s+3)(s+4)}
\]
and in particular this means that if \(\chi'\) is a character mod \(q'\),
\[
    1 \ll \frac{L(1, \chi)\log(q')\log(dq')\vert \ d \vert \ ^{10\epsilon}}{\epsilon} + O(\vert \ d \vert \ ^{-5})
\]
and so
\[
    L(1, \chi) \gg_\epsilon \vert \ d  \vert \ ^{-\epsilon}
\]
